
staticmanUrl: https://anasbasem.herokuapp.com/v2/entry/basemwahba/allah/master/comments
enableComments: true

# reCAPTCHA keys
reCaptcha:
  siteKey: "6LdX298UAAAAANl1cTQ6jipGZxl8VgoSzCZr07E3"
  secret: "6LdX298UAAAAAJ0G_LKHW5tHvQII2OlgPj9_IIBo"
